version: "3.7"
services:
  mongo5:
    image: prismagraphql/mongo-single-replica:5.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "prisma"
      MONGO_INITDB_ROOT_PASSWORD: "prisma"
      MONGO_PORT: 27018
    ports:
      - "27018:27018"
    networks:
      - databases
networks:
  databases: null